openapi: "3.1.0"
info:
  title: "Privacy Policy"
  version: "1.0.0"
  description: "OpenAPI spec for fetching the IT Transformation Advisor privacy policy."

servers:
  - url: "https://privacy-z0u7.onrender.com"
    description: "Privacy policy host"

paths:
  /privacy.yaml:
    get:
      operationId: getPrivacyPolicy
      summary: "Retrieve Privacy Policy"
      description: "Returns the IT Transformation Advisor Privacy Policy in YAML format."
      responses:
        "200":
          description: "Privacy Policy YAML"
          content:
            application/x-yaml:
              schema:
                type: string
