openapi: "3.1.0"
info:
  title: "Privacy Policy"
  version: "1.0.0"        # must be a string
  description: |
    The privacy policy for the IT Transformation Advisor GPT.

servers:
  - url: "https://privacy-z0u7.onrender.com"
    description: Privacy policy host

paths:
  /privacy.yaml:
    get:
      summary: Retrieve the Privacy Policy
      description: |
        **Effective Date:** May 1, 2025

        The IT Transformation Advisor GPT does not collect, store, or share any personal data. All files uploaded during your session are stored temporarily in a secure Google Drive folder. These folders are automatically deleted if no files are uploaded within 5 minutes or once analysis is complete.

        We do not retain uploaded files, email addresses, session data, or conversation history beyond the execution period of your analysis.

        This tool is provided for advisory purposes only. Use of this system implies consent to this temporary handling of data as part of the automation process.

        **For questions, please contact:** ittransformationadvisor@gmail.com

        **Terms of Use**  
        By using the IT Transformation Advisor GPT and its supporting tools (including the Google Form, Drive automation, and GPT-driven modules), you agree to the following:

        1. **Purpose**  
           This tool is provided as an advisory system to assist organizations in evaluating and modernizing their IT infrastructure using AI-based insights. It is not intended to replace professional consulting services.

        2. **Data Responsibility**  
           Users are responsible for the accuracy, relevance, and sensitivity of the data they upload. Please **do not upload confidential, personal, or regulated data**.

        3. **Session Handling**  
           Uploaded files are processed temporarily and deleted automatically after:
           - 5 minutes of inactivity (no uploads), or  
           - Completion of analysis and ZIP delivery.  

           The system does not retain any user data beyond the session.

        4. **No Guarantees**  
           While the GPT modules are built with high accuracy and industry logic, the insights and reports generated are for informational purposes only and may not be fully exhaustive or error-free.

        5. **Use at Your Own Risk**  
           The IT Transformation Advisor is provided “as is” without warranties of any kind. Users assume full responsibility for how the reports are interpreted and used in decision-making.
      responses:
        "200":
          description: Returns the Privacy Policy in YAML format
          content:
            application/x-yaml:
              schema:
                type: string
